project_id = "mfirmyahzixjbjauunhs"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.create-sourcecode-order]
verify_jwt = false

[functions.verify-sourcecode-payment]
verify_jwt = false
